export const ChatConstants = {
  emoji: () =>
    String.fromCodePoint(0x1f_300 + Math.floor(Math.random() * 0x2ff)),

  separator: () =>
    [
      '-',
      '•',
      '–',
      '—',
      '~',
      '|',
      '/',
      '\\',
      ':',
      '::',
      '→',
      '⇒',
      '⟶',
      '⇢',
      '➤',
      '➜',
      '≫',
      '»',
      '>>',
      '«',
      '‹',
      '⋆',
      '✶',
      '✦',
      '✧',
      '★',
      '☆',
      '✪',
      '✩',
      '⬩',
      '❖',
      '◆',
      '◇',
      '¤',
      '•̷',
      '✱',
      '✳',
      '✴',
      '❈',
      '❉',
      '⊳',
      '⫷',
      '⫸',
      '⋄',
      '⌁',
      '⊱',
      '⊰',
      '╌',
      '╍',
    ][Math.floor(Math.random() * 50)],

  text: () =>
    [
      'Sparks of Thought',
      'Deep Dive on',
      'A Chat From',
      'Unlocked Ideas',
      'Notes from',
      'You & AI',
      'Memory Log',
      'Insightful Session',
      'Highlights of',
      'Reflections on',
      'Freestyle Flow',
      'Brainstorm Launch',
      'Thought Bubble',
      'Auto-Generated Log',
      'Session Recap',
      'Lightbulb Moment',
      'Unfiltered Thoughts',
      'Conversation Replay',
      'Mind Sync',
      'Creative Burst',
      'Open Dialogue',
      'AI-Enhanced Talk',
      'Unscripted Ideas',
      'Ideas in Motion',
      'Neural Exchange',
      'Rapid Reflections',
      'Timeless Talk',
      'Cognitive Sparks',
      'Unlocked Memory',
      'Daydream Dialogue',
      'Synapse Session',
      'Insight Explosion',
      'Fragments of Genius',
      'Unedited Thoughts',
      'Echoes of Thought',
      'MindMap Session',
      'Focus Mode: On',
      'Introspective Flow',
      'AI Jam Session',
      'Reflection Loop',
      'Rethink Log',
      'Bold Thought Drop',
      'Clarity in Chaos',
      'Dialog Drift',
      'Mental Download',
      'Purposeful Pause',
      'Flashback Frame',
      'Memory Capsule',
      'Unboxed Ideas',
      'Vivid Exchange',
      'Exploration Mode',
      'Open Loop Chat',
      'Rewired Talk',
      'Unraveled Mind',
      'The Think Tank',
      'Afterglow Log',
      'Unlocked Patterns',
      'Flicker of Insight',
      'Chronicle of Thought',
      'Beyond the Surface',
      'Realtime Mindshare',
      'Fragments from Today',
      'Micro Moments',
      'Thoughts Unleashed',
      'In Retrospect',
      'Mental Vibes',
      'Silent Genius',
      'Cognitive Circuit',
      'Dialog Frame',
      'Session of Signals',
      'Trail of Thought',
      'Creative Circuit',
      'Neural Sparks',
      'The Raw Feed',
      'Internal Monologue',
      'Decoded Mindset',
      'Vision Snapshot',
      'Unlocked Session',
      'Deep Archive',
      'Signals from Self',
      'Mental Snapshot',
      'Realizations in Real Time',
      'Clarity Log',
      'One Take Talk',
      'Conscious Unload',
      'Silent Notes',
      'From the Core',
      'The Loop Recorder',
      'Raw Mindplay',
      'Candid Thoughts',
      'Still Processing',
      'Dialog Pulse',
      'Wisdom Stream',
      'Channeling Insight',
      'Thinking Out Loud',
      'Next-Level Thought',
      'The Inner Voice',
      'Echo Journal',
      'Conversation Trail',
      'Realtime Realizations',
      'Present Mindscape',
      'Dialogue Snapshot',
      'Mindstream Playback',
    ][Math.floor(Math.random() * 103)],

  date: () =>
    new Date().toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
};
